import "./globals.css";
import type { Metadata } from "next";
import { noto_Sans_JP, open_Sans } from "./fonts";

import Header from "../components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html
            lang="ja"
            suppressHydrationWarning={true}
            className={`${noto_Sans_JP.variable} ${open_Sans.variable}`}
        >
            <body className="bg-gray-900 text-white">
                <Header></Header>
                <main className="">{children}</main>
                <Toaster></Toaster>
                <Footer></Footer>
            </body>
        </html>
    );
}
